# Generated by Django 4.0.4 on 2022-05-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('continent', models.CharField(max_length=255, verbose_name='continent')),
                ('acronym', models.CharField(max_length=3, unique=True, verbose_name='acronym')),
            ],
        ),
    ]
