# Generated by Django 4.0.4 on 2022-05-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_country_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='acronym',
            field=models.CharField(max_length=3, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(max_length=255, verbose_name='Continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
