# Generated by Django 4.0.4 on 2022-05-16 20:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_hostcountry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostcountry',
            name='country_ptr',
        ),
        migrations.AddField(
            model_name='hostcountry',
            name='country',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='countries.country', verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostcountry',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
