-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.countries
(
    id integer NOT NULL,
    name character varying NOT NULL,
    acronym character varying(3) NOT NULL,
    continent character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.phases
(
    id integer NOT NULL,
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.championships
(
    id integer NOT NULL,
    year integer NOT NULL,
    countries integer NOT NULL,
    goals integer NOT NULL,
    golden_ball integer DEFAULT NULL,
    golden_boot integer DEFAULT NULL,
    golden_glove integer DEFAULT NULL,
    audience integer DEFAULT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS public.rankings
(
    id integer NOT NULL,
    id_championship integer NOT NULL,
    id_country integer NOT NULL,
    "position" integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.host_countries
(
    id integer NOT NULL,
    id_championship integer NOT NULL,
    id_country integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.players
(
    id integer NOT NULL,
    id_country integer NOT NULL,
    full_name character varying NOT NULL,
    shirt_name character varying NOT NULL,
    birth_date date NOT NULL,
    "position" character(2) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.games
(
    id integer NOT NULL,
    id_championship integer NOT NULL,
    id_phase integer NOT NULL,
    id_country_home integer NOT NULL,
    id_country_guest integer NOT NULL,
    id_stadium integer NOT NULL,
    goals_country_home integer NOT NULL,
    goals_country_guest integer NOT NULL,
    tickets integer NOT NULL,
    date timestamp without time zone NOT NULL,
    win_conditions character varying DEFAULT NULL,
    audience integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.stadiums
(
    id integer NOT NULL,
    id_country integer NOT NULL,
    name character varying NOT NULL,
    city character varying NOT NULL,
    capacity integer DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cards
(
    id integer NOT NULL,
    id_game integer NOT NULL,
    id_player integer NOT NULL,
    color character(1) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.rankings
    ADD CONSTRAINT fk_country FOREIGN KEY (id_country)
    REFERENCES public.countries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.rankings
    ADD CONSTRAINT fk_championship FOREIGN KEY (id_championship)
    REFERENCES public.championships (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.host_countries
    ADD CONSTRAINT fk_championship FOREIGN KEY (id_championship)
    REFERENCES public.championships (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.host_countries
    ADD CONSTRAINT fk_country FOREIGN KEY (id_country)
    REFERENCES public.countries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.players
    ADD CONSTRAINT fk_country FOREIGN KEY (id_country)
    REFERENCES public.countries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.games
    ADD CONSTRAINT fk_championship FOREIGN KEY (id_championship)
    REFERENCES public.championships (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.games
    ADD CONSTRAINT fk_phase FOREIGN KEY (id_phase)
    REFERENCES public.phases (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.games
    ADD CONSTRAINT fk_country_home FOREIGN KEY (id_country_home)
    REFERENCES public.countries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.games
    ADD CONSTRAINT fk_country_guest FOREIGN KEY (id_country_guest)
    REFERENCES public.countries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.games
    ADD CONSTRAINT fk_stadium FOREIGN KEY (id_stadium)
    REFERENCES public.stadiums (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.stadiums
    ADD CONSTRAINT fk_country FOREIGN KEY (id_country)
    REFERENCES public.countries (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.cards
    ADD CONSTRAINT fk_player FOREIGN KEY (id_player)
    REFERENCES public.players (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public.cards
    ADD CONSTRAINT fk_game FOREIGN KEY (id_game)
    REFERENCES public.games (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;