# Generated by Django 4.0.4 on 2022-05-16 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0004_hostcountry'),
        ('championships', '0002_rename_total_contries_championship_total_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='championships.championship', verbose_name='Championship')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries.country', verbose_name='Country')),
            ],
        ),
    ]
