# Generated by Django 4.0.4 on 2022-05-17 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('championships', '0003_alter_championship_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='golden_ball',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_golden_ball', to='players.player', verbose_name='Golden Ball'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='golden_boot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_golden_boot', to='players.player', verbose_name='Golden Boot'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='golden_glove',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_golden_glove', to='players.player', verbose_name='Golden Glove'),
        ),
    ]
