# Generated by Django 4.0.4 on 2022-05-16 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0002_rename_total_contries_championship_total_countries'),
        ('countries', '0003_alter_country_acronym_alter_country_continent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostCountry',
            fields=[
                ('country_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='countries.country')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='championships.championship', verbose_name='Championship')),
            ],
            bases=('countries.country',),
        ),
    ]
