# Generated by Django 4.0.4 on 2022-05-17 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_hostcountry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostcountry',
            name='country_ptr',
        ),
        migrations.AddField(
            model_name='hostcountry',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='countries.country', verbose_name='Country'),
            preserve_default=False,
        ),
    ]
