# Generated by Django 4.0.4 on 2022-05-17 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_remove_hostcountry_country_ptr_hostcountry_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostCountry',
        ),
    ]
