# Generated by Django 4.0.4 on 2022-05-17 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0002_rename_total_contries_championship_total_countries'),
        ('countries', '0006_delete_hostcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='championship', to='championships.championship', verbose_name='Championship')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='country', to='countries.country', verbose_name='Country')),
            ],
        ),
    ]
