# Generated by Django 4.0.4 on 2022-05-17 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0004_alter_championship_golden_ball_and_more'),
        ('countries', '0007_hostcountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostcountry',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_championship', to='championships.championship', verbose_name='Championship'),
        ),
        migrations.AlterField(
            model_name='hostcountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_country', to='countries.country', verbose_name='Country'),
        ),
    ]
