# Generated by Django 2.2.1 on 2022-07-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0008_alter_hostcountry_championship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='acronym',
        ),
        migrations.AddField(
            model_name='country',
            name='coi_acronym',
            field=models.CharField(default='AAA', max_length=3, verbose_name='COI Acronym'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hostcountry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
