# Generated by Django 4.0.4 on 2022-05-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Year')),
                ('total_contries', models.IntegerField(verbose_name='Total Countries')),
                ('total_goals', models.IntegerField(verbose_name='Total Goals')),
                ('total_audience', models.IntegerField(verbose_name='Total Audience')),
                ('golden_ball', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_golden_ball', to='players.player', verbose_name='Golden Ball')),
                ('golden_boot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_golden_boot', to='players.player', verbose_name='Golden Boot')),
                ('golden_glove', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_golden_glove', to='players.player', verbose_name='Golden Glove')),
            ],
        ),
    ]
