# Generated by Django 4.0.4 on 2022-05-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0002_rename_total_contries_championship_total_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='year',
            field=models.CharField(max_length=4, unique=True, verbose_name='Year'),
        ),
    ]
