# Generated by Django 4.0.4 on 2022-05-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0002_alter_country_acronym'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('capacity', models.IntegerField(null=True, verbose_name='Capacity')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries.country', verbose_name='Country')),
            ],
        ),
    ]
